// Typography Compositions for Instagram Post Generator
// 40 compositions in 8 categories (5 per category)
// Canvas: 1080x1080px — text over images, white text with shadows/strokes

export interface TypographyComposition {
  id: string;
  name: string;
  category:
    | "modern"
    | "elegant"
    | "bold"
    | "playful"
    | "minimal"
    | "editorial"
    | "street"
    | "luxury";
  previewText: { headline: string; subtitle?: string; cta?: string };
  layers: Array<{
    role: "headline" | "subtitle" | "cta" | "decoration";
    type: "textbox";
    props: {
      text: string;
      left: number;
      top: number;
      originX: "left" | "center" | "right";
      originY: "top" | "center" | "bottom";
      width: number;
      fontSize: number;
      fontFamily: string;
      fontWeight: string;
      fill: string;
      textAlign: "left" | "center" | "right";
      charSpacing?: number;
      lineHeight?: number;
      opacity?: number;
      stroke?: string;
      strokeWidth?: number;
      shadow?: {
        color: string;
        blur: number;
        offsetX: number;
        offsetY: number;
      };
      fontStyle?: "normal" | "italic";
      textTransform?: "uppercase" | "none";
    };
  }>;
  overlays?: Array<{
    type: "rect" | "circle";
    props: Record<string, any>;
  }>;
}

// ---------------------------------------------------------------------------
// MODERN (5) — Clean sans-serif combos
// ---------------------------------------------------------------------------

const modern: TypographyComposition[] = [
  {
    id: "modern-centered-clean",
    name: "Moderno Centralizado",
    category: "modern",
    previewText: {
      headline: "SEU TITULO AQUI",
      subtitle: "Subtitulo descritivo do seu post",
      cta: "SAIBA MAIS",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "SEU TITULO AQUI",
          left: 540,
          top: 400,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 72,
          fontFamily: "Inter",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: -20,
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 12, offsetX: 0, offsetY: 4 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Subtitulo descritivo do seu post",
          left: 540,
          top: 520,
          originX: "center",
          originY: "center",
          width: 750,
          fontSize: 28,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "SAIBA MAIS",
          left: 540,
          top: 620,
          originX: "center",
          originY: "center",
          width: 300,
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 300,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "modern-left-stack",
    name: "Moderno Empilhado Esquerda",
    category: "modern",
    previewText: {
      headline: "DESIGN QUE INSPIRA",
      subtitle: "Criatividade sem limites para sua marca",
      cta: "CONFIRA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "DESIGN QUE INSPIRA",
          left: 80,
          top: 380,
          originX: "left",
          originY: "center",
          width: 700,
          fontSize: 68,
          fontFamily: "Space Grotesk",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: -30,
          lineHeight: 1.05,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 14, offsetX: 0, offsetY: 4 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Criatividade sem limites para sua marca",
          left: 80,
          top: 520,
          originX: "left",
          originY: "center",
          width: 600,
          fontSize: 24,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "CONFIRA",
          left: 80,
          top: 600,
          originX: "left",
          originY: "center",
          width: 200,
          fontSize: 16,
          fontFamily: "Space Grotesk",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 400,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "modern-bottom-heavy",
    name: "Moderno Base Forte",
    category: "modern",
    previewText: {
      headline: "NOVA COLECAO",
      subtitle: "Descubra o que preparamos para voce",
      cta: "VER AGORA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "NOVA COLECAO",
          left: 540,
          top: 750,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 80,
          fontFamily: "Outfit",
          fontWeight: "800",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: -10,
          lineHeight: 1.0,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 16, offsetX: 0, offsetY: 4 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Descubra o que preparamos para voce",
          left: 540,
          top: 860,
          originX: "center",
          originY: "center",
          width: 700,
          fontSize: 26,
          fontFamily: "Outfit",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "VER AGORA",
          left: 540,
          top: 940,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 16,
          fontFamily: "Outfit",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 350,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
    overlays: [
      {
        type: "rect",
        props: {
          left: 0,
          top: 680,
          width: 1080,
          height: 400,
          fill: "rgba(0,0,0,0.45)",
        },
      },
    ],
  },
  {
    id: "modern-split-duo",
    name: "Moderno Dividido",
    category: "modern",
    previewText: {
      headline: "TRANSFORME SUAS IDEIAS",
      subtitle: "Do conceito a realidade",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "TRANSFORME SUAS IDEIAS",
          left: 80,
          top: 200,
          originX: "left",
          originY: "top",
          width: 500,
          fontSize: 64,
          fontFamily: "Plus Jakarta Sans",
          fontWeight: "800",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: -20,
          lineHeight: 1.05,
          shadow: { color: "rgba(0,0,0,0.65)", blur: 14, offsetX: 0, offsetY: 4 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Do conceito a realidade",
          left: 80,
          top: 850,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 30,
          fontFamily: "Plus Jakarta Sans",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.4,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "modern-tight-center",
    name: "Moderno Compacto",
    category: "modern",
    previewText: {
      headline: "MENOS E MAIS",
      subtitle: "A simplicidade como estrategia",
      cta: "DESCUBRA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "MENOS E MAIS",
          left: 540,
          top: 460,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 90,
          fontFamily: "DM Sans",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: -40,
          lineHeight: 0.95,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 12, offsetX: 0, offsetY: 4 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "A simplicidade como estrategia",
          left: 540,
          top: 560,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 22,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "DESCUBRA",
          left: 540,
          top: 640,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 14,
          fontFamily: "DM Sans",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 500,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// ELEGANT (5) — Serif + thin sans combos
// ---------------------------------------------------------------------------

const elegant: TypographyComposition[] = [
  {
    id: "elegant-centered-serif",
    name: "Elegante Centralizado",
    category: "elegant",
    previewText: {
      headline: "Arte & Estilo",
      subtitle: "Uma experiencia visual unica",
      cta: "EXPLORAR",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Arte & Estilo",
          left: 540,
          top: 420,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 82,
          fontFamily: "Playfair Display",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
          fontStyle: "italic",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Uma experiencia visual unica",
          left: 540,
          top: 540,
          originX: "center",
          originY: "center",
          width: 650,
          fontSize: 24,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 100,
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "EXPLORAR",
          left: 540,
          top: 640,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 14,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 600,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "elegant-garamond-left",
    name: "Elegante Garamond",
    category: "elegant",
    previewText: {
      headline: "Beleza Natural",
      subtitle: "Descubra a essencia da sofisticacao",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Beleza Natural",
          left: 100,
          top: 440,
          originX: "left",
          originY: "center",
          width: 600,
          fontSize: 76,
          fontFamily: "Cormorant Garamond",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Descubra a essencia da sofisticacao",
          left: 100,
          top: 580,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 50,
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "elegant-lora-bottom",
    name: "Elegante Lora Inferior",
    category: "elegant",
    previewText: {
      headline: "Momentos Especiais",
      subtitle: "Cada detalhe conta uma historia",
      cta: "VEJA MAIS",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Momentos Especiais",
          left: 540,
          top: 720,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 70,
          fontFamily: "Lora",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 12, offsetX: 0, offsetY: 4 },
          fontStyle: "italic",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Cada detalhe conta uma historia",
          left: 540,
          top: 830,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "VEJA MAIS",
          left: 540,
          top: 920,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 13,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 500,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
    overlays: [
      {
        type: "rect",
        props: {
          left: 0,
          top: 640,
          width: 1080,
          height: 440,
          fill: "rgba(0,0,0,0.4)",
        },
      },
    ],
  },
  {
    id: "elegant-dm-serif-center",
    name: "Elegante DM Serif",
    category: "elegant",
    previewText: {
      headline: "Tradicao & Inovacao",
      subtitle: "O melhor dos dois mundos",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Tradicao & Inovacao",
          left: 540,
          top: 440,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 74,
          fontFamily: "DM Serif Display",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.15,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "O melhor dos dois mundos",
          left: 540,
          top: 560,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 20,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 150,
          lineHeight: 1.5,
          opacity: 0.75,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "elegant-eb-garamond-split",
    name: "Elegante EB Garamond",
    category: "elegant",
    previewText: {
      headline: "Exclusividade em Cada Peca",
      subtitle: "Feito para quem valoriza qualidade",
      cta: "CONHECA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Exclusividade em Cada Peca",
          left: 100,
          top: 250,
          originX: "left",
          originY: "top",
          width: 550,
          fontSize: 66,
          fontFamily: "EB Garamond",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.55)", blur: 12, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Feito para quem valoriza qualidade",
          left: 100,
          top: 820,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "CONHECA",
          left: 100,
          top: 900,
          originX: "left",
          originY: "center",
          width: 200,
          fontSize: 14,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 500,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// BOLD (5) — High-impact heavy weight
// ---------------------------------------------------------------------------

const bold: TypographyComposition[] = [
  {
    id: "bold-bebas-impact",
    name: "Impacto Bebas",
    category: "bold",
    previewText: {
      headline: "HORA DE AGIR",
      subtitle: "Nao espere mais",
      cta: "COMECE AGORA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "HORA DE AGIR",
          left: 540,
          top: 440,
          originX: "center",
          originY: "center",
          width: 950,
          fontSize: 130,
          fontFamily: "Bebas Neue",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 50,
          lineHeight: 0.9,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 16, offsetX: 0, offsetY: 6 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Nao espere mais",
          left: 540,
          top: 560,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 28,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "COMECE AGORA",
          left: 540,
          top: 660,
          originX: "center",
          originY: "center",
          width: 350,
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 200,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "bold-oswald-left",
    name: "Impacto Oswald Esquerda",
    category: "bold",
    previewText: {
      headline: "FORCA TOTAL",
      subtitle: "Supere seus limites hoje",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "FORCA TOTAL",
          left: 80,
          top: 420,
          originX: "left",
          originY: "center",
          width: 700,
          fontSize: 110,
          fontFamily: "Oswald",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 0.95,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 14, offsetX: 0, offsetY: 5 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Supere seus limites hoje",
          left: 85,
          top: 560,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 26,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.4,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "bold-anton-full",
    name: "Impacto Anton Cheio",
    category: "bold",
    previewText: {
      headline: "SEM MEDO",
      cta: "AVANCE",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "SEM MEDO",
          left: 540,
          top: 480,
          originX: "center",
          originY: "center",
          width: 1000,
          fontSize: 160,
          fontFamily: "Anton",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 0.9,
          shadow: { color: "rgba(0,0,0,0.8)", blur: 20, offsetX: 0, offsetY: 6 },
          stroke: "rgba(0,0,0,0.3)",
          strokeWidth: 2,
          textTransform: "uppercase",
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "AVANCE",
          left: 540,
          top: 640,
          originX: "center",
          originY: "center",
          width: 300,
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 400,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "bold-archivo-diagonal",
    name: "Impacto Archivo Diagonal",
    category: "bold",
    previewText: {
      headline: "POTENCIA MAXIMA",
      subtitle: "Resultados que impressionam",
      cta: "COMECE JA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "POTENCIA MAXIMA",
          left: 80,
          top: 300,
          originX: "left",
          originY: "top",
          width: 650,
          fontSize: 96,
          fontFamily: "Archivo Black",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 0.95,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 16, offsetX: 0, offsetY: 5 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Resultados que impressionam",
          left: 80,
          top: 700,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 26,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.4,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "COMECE JA",
          left: 80,
          top: 780,
          originX: "left",
          originY: "center",
          width: 250,
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 250,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "bold-dela-gothic-center",
    name: "Impacto Dela Gothic",
    category: "bold",
    previewText: {
      headline: "MUDE O JOGO",
      subtitle: "Sua vez de brilhar",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "MUDE O JOGO",
          left: 540,
          top: 450,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 100,
          fontFamily: "Dela Gothic One",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 0.95,
          shadow: { color: "rgba(0,0,0,0.75)", blur: 18, offsetX: 0, offsetY: 6 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Sua vez de brilhar",
          left: 540,
          top: 580,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 28,
          fontFamily: "DM Sans",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// PLAYFUL (5) — Rounded + colorful
// ---------------------------------------------------------------------------

const playful: TypographyComposition[] = [
  {
    id: "playful-nunito-bounce",
    name: "Divertido Nunito",
    category: "playful",
    previewText: {
      headline: "Vamos Criar Juntos!",
      subtitle: "Diversao garantida para todos",
      cta: "PARTICIPE",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Vamos Criar Juntos!",
          left: 540,
          top: 400,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 72,
          fontFamily: "Nunito",
          fontWeight: "800",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.15,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 4 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Diversao garantida para todos",
          left: 540,
          top: 520,
          originX: "center",
          originY: "center",
          width: 650,
          fontSize: 26,
          fontFamily: "Nunito",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "PARTICIPE",
          left: 540,
          top: 620,
          originX: "center",
          originY: "center",
          width: 300,
          fontSize: 20,
          fontFamily: "Nunito",
          fontWeight: "700",
          fill: "#FFD700",
          textAlign: "center",
          charSpacing: 200,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "playful-fredoka-left",
    name: "Divertido Fredoka",
    category: "playful",
    previewText: {
      headline: "Momento de Alegria",
      subtitle: "Celebre cada conquista",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Momento de Alegria",
          left: 80,
          top: 420,
          originX: "left",
          originY: "center",
          width: 650,
          fontSize: 70,
          fontFamily: "Fredoka",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.15,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 4 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Celebre cada conquista",
          left: 80,
          top: 570,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 26,
          fontFamily: "Fredoka",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "playful-baloo-center",
    name: "Divertido Baloo",
    category: "playful",
    previewText: {
      headline: "Sorria Mais!",
      subtitle: "A vida e feita de momentos felizes",
      cta: "CURTA AGORA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Sorria Mais!",
          left: 540,
          top: 380,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 86,
          fontFamily: "Baloo 2",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 12, offsetX: 0, offsetY: 4 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "A vida e feita de momentos felizes",
          left: 540,
          top: 510,
          originX: "center",
          originY: "center",
          width: 700,
          fontSize: 24,
          fontFamily: "Nunito",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "CURTA AGORA",
          left: 540,
          top: 620,
          originX: "center",
          originY: "center",
          width: 350,
          fontSize: 18,
          fontFamily: "Nunito",
          fontWeight: "700",
          fill: "#FF6B6B",
          textAlign: "center",
          charSpacing: 200,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "playful-boogaloo-bottom",
    name: "Divertido Boogaloo",
    category: "playful",
    previewText: {
      headline: "Vem com a Gente!",
      subtitle: "Uma jornada incrivel espera por voce",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Vem com a Gente!",
          left: 540,
          top: 740,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 78,
          fontFamily: "Boogaloo",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 12, offsetX: 0, offsetY: 4 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Uma jornada incrivel espera por voce",
          left: 540,
          top: 860,
          originX: "center",
          originY: "center",
          width: 650,
          fontSize: 24,
          fontFamily: "Nunito",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
    ],
    overlays: [
      {
        type: "rect",
        props: {
          left: 0,
          top: 660,
          width: 1080,
          height: 420,
          fill: "rgba(0,0,0,0.4)",
        },
      },
    ],
  },
  {
    id: "playful-righteous-split",
    name: "Divertido Righteous",
    category: "playful",
    previewText: {
      headline: "Energia Pura",
      subtitle: "Cada dia e uma nova oportunidade",
      cta: "BORA LA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Energia Pura",
          left: 540,
          top: 300,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 80,
          fontFamily: "Righteous",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 4 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Cada dia e uma nova oportunidade",
          left: 540,
          top: 750,
          originX: "center",
          originY: "center",
          width: 650,
          fontSize: 26,
          fontFamily: "Nunito",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "BORA LA",
          left: 540,
          top: 840,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 20,
          fontFamily: "Righteous",
          fontWeight: "400",
          fill: "#4ECDC4",
          textAlign: "center",
          charSpacing: 200,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// MINIMAL (5) — Ultra-clean, lots of whitespace
// ---------------------------------------------------------------------------

const minimal: TypographyComposition[] = [
  {
    id: "minimal-inter-light",
    name: "Minimalista Inter",
    category: "minimal",
    previewText: {
      headline: "Simplicidade",
      subtitle: "O essencial e invisivel aos olhos",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Simplicidade",
          left: 540,
          top: 480,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 64,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 80,
          lineHeight: 1.2,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "O essencial e invisivel aos olhos",
          left: 540,
          top: 580,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 100,
          lineHeight: 1.6,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "minimal-raleway-left",
    name: "Minimalista Raleway",
    category: "minimal",
    previewText: {
      headline: "ESPACO",
      subtitle: "Respire fundo e encontre clareza",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "ESPACO",
          left: 100,
          top: 480,
          originX: "left",
          originY: "center",
          width: 600,
          fontSize: 72,
          fontFamily: "Raleway",
          fontWeight: "200",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 400,
          lineHeight: 1.2,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 8, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Respire fundo e encontre clareza",
          left: 100,
          top: 580,
          originX: "left",
          originY: "center",
          width: 450,
          fontSize: 18,
          fontFamily: "Raleway",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.6,
          opacity: 0.65,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "minimal-barlow-bottom",
    name: "Minimalista Barlow",
    category: "minimal",
    previewText: {
      headline: "FOCO",
      subtitle: "No que realmente importa",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "FOCO",
          left: 540,
          top: 800,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 80,
          fontFamily: "Barlow",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 600,
          lineHeight: 1.2,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 8, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "No que realmente importa",
          left: 540,
          top: 890,
          originX: "center",
          originY: "center",
          width: 400,
          fontSize: 16,
          fontFamily: "Barlow",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 150,
          lineHeight: 1.6,
          opacity: 0.6,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "minimal-rubik-center",
    name: "Minimalista Rubik",
    category: "minimal",
    previewText: {
      headline: "Clareza",
      subtitle: "Menos ruido, mais significado",
      cta: "SAIBA MAIS",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Clareza",
          left: 540,
          top: 440,
          originX: "center",
          originY: "center",
          width: 700,
          fontSize: 70,
          fontFamily: "Rubik",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 60,
          lineHeight: 1.2,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Menos ruido, mais significado",
          left: 540,
          top: 540,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 18,
          fontFamily: "Rubik",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 80,
          lineHeight: 1.6,
          opacity: 0.65,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "SAIBA MAIS",
          left: 540,
          top: 640,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 12,
          fontFamily: "Rubik",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 500,
          opacity: 0.5,
          shadow: { color: "rgba(0,0,0,0.2)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "minimal-montserrat-airy",
    name: "Minimalista Montserrat",
    category: "minimal",
    previewText: {
      headline: "EQUILIBRIO",
      subtitle: "Harmonia em cada detalhe",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "EQUILIBRIO",
          left: 540,
          top: 460,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 58,
          fontFamily: "Montserrat",
          fontWeight: "200",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 500,
          lineHeight: 1.2,
          shadow: { color: "rgba(0,0,0,0.35)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Harmonia em cada detalhe",
          left: 540,
          top: 560,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 16,
          fontFamily: "Montserrat",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 150,
          lineHeight: 1.6,
          opacity: 0.6,
          shadow: { color: "rgba(0,0,0,0.25)", blur: 4, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// EDITORIAL (5) — Magazine-style combos
// ---------------------------------------------------------------------------

const editorial: TypographyComposition[] = [
  {
    id: "editorial-dm-serif-magazine",
    name: "Editorial DM Serif",
    category: "editorial",
    previewText: {
      headline: "A Nova Era do Design",
      subtitle: "Tendencias que vao transformar o mercado em 2026",
      cta: "LEIA MAIS",
    },
    layers: [
      {
        role: "decoration",
        type: "textbox",
        props: {
          text: "TENDENCIA",
          left: 540,
          top: 280,
          originX: "center",
          originY: "center",
          width: 400,
          fontSize: 12,
          fontFamily: "DM Sans",
          fontWeight: "500",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 800,
          opacity: 0.6,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "A Nova Era do Design",
          left: 540,
          top: 420,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 74,
          fontFamily: "DM Serif Display",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Tendencias que vao transformar o mercado em 2026",
          left: 540,
          top: 560,
          originX: "center",
          originY: "center",
          width: 650,
          fontSize: 22,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "LEIA MAIS",
          left: 540,
          top: 660,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 13,
          fontFamily: "DM Sans",
          fontWeight: "500",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 500,
          opacity: 0.65,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "editorial-playfair-left",
    name: "Editorial Playfair Esquerda",
    category: "editorial",
    previewText: {
      headline: "Entrevista Exclusiva",
      subtitle: "Os segredos por tras do sucesso das grandes marcas",
    },
    layers: [
      {
        role: "decoration",
        type: "textbox",
        props: {
          text: "EXCLUSIVO",
          left: 100,
          top: 280,
          originX: "left",
          originY: "center",
          width: 300,
          fontSize: 12,
          fontFamily: "Inter",
          fontWeight: "500",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 700,
          opacity: 0.6,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Entrevista Exclusiva",
          left: 100,
          top: 420,
          originX: "left",
          originY: "center",
          width: 600,
          fontSize: 68,
          fontFamily: "Playfair Display",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
          fontStyle: "italic",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Os segredos por tras do sucesso das grandes marcas",
          left: 100,
          top: 590,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "editorial-lora-grotesk",
    name: "Editorial Lora + Grotesk",
    category: "editorial",
    previewText: {
      headline: "Cultura & Sociedade",
      subtitle: "Um olhar critico sobre o mundo contemporaneo",
      cta: "CONTINUE LENDO",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Cultura & Sociedade",
          left: 540,
          top: 380,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 72,
          fontFamily: "Lora",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Um olhar critico sobre o mundo contemporaneo",
          left: 540,
          top: 510,
          originX: "center",
          originY: "center",
          width: 650,
          fontSize: 22,
          fontFamily: "Space Grotesk",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "CONTINUE LENDO",
          left: 540,
          top: 610,
          originX: "center",
          originY: "center",
          width: 350,
          fontSize: 13,
          fontFamily: "Space Grotesk",
          fontWeight: "500",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 400,
          opacity: 0.65,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "editorial-cover-style",
    name: "Editorial Capa",
    category: "editorial",
    previewText: {
      headline: "O Futuro Comeca Aqui",
      subtitle: "Especial 2026",
    },
    layers: [
      {
        role: "decoration",
        type: "textbox",
        props: {
          text: "EDICAO ESPECIAL",
          left: 540,
          top: 150,
          originX: "center",
          originY: "center",
          width: 400,
          fontSize: 14,
          fontFamily: "Inter",
          fontWeight: "500",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 600,
          opacity: 0.6,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "O Futuro Comeca Aqui",
          left: 540,
          top: 540,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 80,
          fontFamily: "Playfair Display",
          fontWeight: "900",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.05,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 14, offsetX: 0, offsetY: 4 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Especial 2026",
          left: 540,
          top: 700,
          originX: "center",
          originY: "center",
          width: 400,
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 300,
          lineHeight: 1.5,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "editorial-column-right",
    name: "Editorial Coluna Direita",
    category: "editorial",
    previewText: {
      headline: "Perspectivas do Amanha",
      subtitle: "Analise aprofundada sobre inovacao e tecnologia",
      cta: "ARTIGO COMPLETO",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Perspectivas do Amanha",
          left: 980,
          top: 400,
          originX: "right",
          originY: "center",
          width: 500,
          fontSize: 62,
          fontFamily: "DM Serif Display",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "right",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Analise aprofundada sobre inovacao e tecnologia",
          left: 980,
          top: 570,
          originX: "right",
          originY: "center",
          width: 450,
          fontSize: 20,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "right",
          lineHeight: 1.5,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "ARTIGO COMPLETO",
          left: 980,
          top: 670,
          originX: "right",
          originY: "center",
          width: 350,
          fontSize: 12,
          fontFamily: "DM Sans",
          fontWeight: "500",
          fill: "#FFFFFF",
          textAlign: "right",
          charSpacing: 400,
          opacity: 0.6,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// STREET (5) — Urban/graffiti feel
// ---------------------------------------------------------------------------

const street: TypographyComposition[] = [
  {
    id: "street-marker-raw",
    name: "Street Marker",
    category: "street",
    previewText: {
      headline: "SEM REGRAS",
      subtitle: "A rua e o nosso palco",
      cta: "COLA AI",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "SEM REGRAS",
          left: 540,
          top: 440,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 100,
          fontFamily: "Permanent Marker",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.0,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 14, offsetX: 3, offsetY: 5 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "A rua e o nosso palco",
          left: 540,
          top: 570,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 26,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "COLA AI",
          left: 540,
          top: 670,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 20,
          fontFamily: "Permanent Marker",
          fontWeight: "400",
          fill: "#FF4444",
          textAlign: "center",
          charSpacing: 150,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 8, offsetX: 2, offsetY: 3 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "street-alfa-slab-left",
    name: "Street Alfa Slab",
    category: "street",
    previewText: {
      headline: "ATITUDE REAL",
      subtitle: "Autenticidade acima de tudo",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "ATITUDE REAL",
          left: 80,
          top: 440,
          originX: "left",
          originY: "center",
          width: 700,
          fontSize: 88,
          fontFamily: "Alfa Slab One",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 0.95,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 16, offsetX: 2, offsetY: 5 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Autenticidade acima de tudo",
          left: 85,
          top: 590,
          originX: "left",
          originY: "center",
          width: 500,
          fontSize: 24,
          fontFamily: "Inter",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.4,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
    ],
  },
  {
    id: "street-blackops-center",
    name: "Street Black Ops",
    category: "street",
    previewText: {
      headline: "UNDERGROUND",
      cta: "ENTRE NO JOGO",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "UNDERGROUND",
          left: 540,
          top: 480,
          originX: "center",
          originY: "center",
          width: 950,
          fontSize: 96,
          fontFamily: "Black Ops One",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.0,
          shadow: { color: "rgba(0,0,0,0.8)", blur: 18, offsetX: 0, offsetY: 6 },
          stroke: "rgba(255,255,255,0.15)",
          strokeWidth: 1,
          textTransform: "uppercase",
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "ENTRE NO JOGO",
          left: 540,
          top: 620,
          originX: "center",
          originY: "center",
          width: 350,
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 250,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "street-anton-stacked",
    name: "Street Anton Empilhado",
    category: "street",
    previewText: {
      headline: "VIVE A VIDA",
      subtitle: "Cada momento e unico",
      cta: "SEGUE O FLUXO",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "VIVE A VIDA",
          left: 540,
          top: 380,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 120,
          fontFamily: "Anton",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 0.9,
          shadow: { color: "rgba(0,0,0,0.7)", blur: 16, offsetX: 0, offsetY: 5 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Cada momento e unico",
          left: 540,
          top: 520,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 26,
          fontFamily: "Space Grotesk",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "SEGUE O FLUXO",
          left: 540,
          top: 620,
          originX: "center",
          originY: "center",
          width: 350,
          fontSize: 18,
          fontFamily: "Permanent Marker",
          fontWeight: "400",
          fill: "#FFA500",
          textAlign: "center",
          charSpacing: 100,
          shadow: { color: "rgba(0,0,0,0.6)", blur: 8, offsetX: 2, offsetY: 3 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "street-oswald-bottom",
    name: "Street Oswald Inferior",
    category: "street",
    previewText: {
      headline: "REPRESENTE",
      subtitle: "Sua voz importa",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "REPRESENTE",
          left: 540,
          top: 760,
          originX: "center",
          originY: "center",
          width: 900,
          fontSize: 110,
          fontFamily: "Oswald",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 0.95,
          shadow: { color: "rgba(0,0,0,0.75)", blur: 18, offsetX: 0, offsetY: 6 },
          textTransform: "uppercase",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Sua voz importa",
          left: 540,
          top: 880,
          originX: "center",
          originY: "center",
          width: 400,
          fontSize: 24,
          fontFamily: "DM Sans",
          fontWeight: "400",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.4,
          opacity: 0.85,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
    ],
    overlays: [
      {
        type: "rect",
        props: {
          left: 0,
          top: 680,
          width: 1080,
          height: 400,
          fill: "rgba(0,0,0,0.5)",
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// LUXURY (5) — Premium brand feel
// ---------------------------------------------------------------------------

const luxury: TypographyComposition[] = [
  {
    id: "luxury-cormorant-center",
    name: "Luxo Cormorant",
    category: "luxury",
    previewText: {
      headline: "Refinamento Absoluto",
      subtitle: "Uma experiencia exclusiva para voce",
      cta: "DESCUBRA",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Refinamento Absoluto",
          left: 540,
          top: 420,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 72,
          fontFamily: "Cormorant Garamond",
          fontWeight: "600",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 30,
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 8, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Uma experiencia exclusiva para voce",
          left: 540,
          top: 540,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 16,
          fontFamily: "Montserrat",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 300,
          lineHeight: 1.6,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "DESCUBRA",
          left: 540,
          top: 640,
          originX: "center",
          originY: "center",
          width: 250,
          fontSize: 12,
          fontFamily: "Montserrat",
          fontWeight: "400",
          fill: "#D4AF37",
          textAlign: "center",
          charSpacing: 600,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "luxury-eb-garamond-left",
    name: "Luxo EB Garamond",
    category: "luxury",
    previewText: {
      headline: "Legado de Excelencia",
      subtitle: "Qualidade que transcende geracoes",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Legado de Excelencia",
          left: 100,
          top: 440,
          originX: "left",
          originY: "center",
          width: 550,
          fontSize: 66,
          fontFamily: "EB Garamond",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "left",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 8, offsetX: 0, offsetY: 2 },
          fontStyle: "italic",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Qualidade que transcende geracoes",
          left: 100,
          top: 590,
          originX: "left",
          originY: "center",
          width: 450,
          fontSize: 16,
          fontFamily: "Raleway",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "left",
          charSpacing: 200,
          lineHeight: 1.6,
          opacity: 0.7,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "luxury-playfair-gold",
    name: "Luxo Playfair Dourado",
    category: "luxury",
    previewText: {
      headline: "Colecao Premium",
      subtitle: "Exclusividade e sofisticacao em cada detalhe",
      cta: "RESERVE AGORA",
    },
    layers: [
      {
        role: "decoration",
        type: "textbox",
        props: {
          text: "PREMIUM",
          left: 540,
          top: 300,
          originX: "center",
          originY: "center",
          width: 300,
          fontSize: 12,
          fontFamily: "Montserrat",
          fontWeight: "400",
          fill: "#D4AF37",
          textAlign: "center",
          charSpacing: 800,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Colecao Premium",
          left: 540,
          top: 440,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 78,
          fontFamily: "Playfair Display",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Exclusividade e sofisticacao em cada detalhe",
          left: 540,
          top: 570,
          originX: "center",
          originY: "center",
          width: 600,
          fontSize: 18,
          fontFamily: "Montserrat",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 100,
          lineHeight: 1.5,
          opacity: 0.75,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "RESERVE AGORA",
          left: 540,
          top: 670,
          originX: "center",
          originY: "center",
          width: 300,
          fontSize: 12,
          fontFamily: "Montserrat",
          fontWeight: "400",
          fill: "#D4AF37",
          textAlign: "center",
          charSpacing: 500,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
  {
    id: "luxury-cormorant-bottom",
    name: "Luxo Cormorant Inferior",
    category: "luxury",
    previewText: {
      headline: "Onde o Luxo Encontra a Arte",
      subtitle: "Pecas selecionadas a mao",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Onde o Luxo Encontra a Arte",
          left: 540,
          top: 740,
          originX: "center",
          originY: "center",
          width: 850,
          fontSize: 64,
          fontFamily: "Cormorant Garamond",
          fontWeight: "700",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.1,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
          fontStyle: "italic",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "Pecas selecionadas a mao",
          left: 540,
          top: 860,
          originX: "center",
          originY: "center",
          width: 500,
          fontSize: 15,
          fontFamily: "Montserrat",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 350,
          lineHeight: 1.6,
          opacity: 0.65,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
    overlays: [
      {
        type: "rect",
        props: {
          left: 0,
          top: 650,
          width: 1080,
          height: 430,
          fill: "rgba(0,0,0,0.45)",
        },
      },
    ],
  },
  {
    id: "luxury-playfair-split",
    name: "Luxo Playfair Dividido",
    category: "luxury",
    previewText: {
      headline: "Atemporal",
      subtitle: "O verdadeiro luxo nunca sai de moda",
      cta: "EXPLORE",
    },
    layers: [
      {
        role: "headline",
        type: "textbox",
        props: {
          text: "Atemporal",
          left: 540,
          top: 300,
          originX: "center",
          originY: "center",
          width: 800,
          fontSize: 90,
          fontFamily: "Playfair Display",
          fontWeight: "900",
          fill: "#FFFFFF",
          textAlign: "center",
          lineHeight: 1.0,
          shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
          fontStyle: "italic",
        },
      },
      {
        role: "subtitle",
        type: "textbox",
        props: {
          text: "O verdadeiro luxo nunca sai de moda",
          left: 540,
          top: 780,
          originX: "center",
          originY: "center",
          width: 550,
          fontSize: 20,
          fontFamily: "Raleway",
          fontWeight: "300",
          fill: "#FFFFFF",
          textAlign: "center",
          charSpacing: 100,
          lineHeight: 1.5,
          opacity: 0.75,
          shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
        },
      },
      {
        role: "cta",
        type: "textbox",
        props: {
          text: "EXPLORE",
          left: 540,
          top: 860,
          originX: "center",
          originY: "center",
          width: 200,
          fontSize: 12,
          fontFamily: "Raleway",
          fontWeight: "400",
          fill: "#D4AF37",
          textAlign: "center",
          charSpacing: 600,
          opacity: 0.8,
          shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 0, offsetY: 2 },
          textTransform: "uppercase",
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Combined export
// ---------------------------------------------------------------------------

export const TYPOGRAPHY_COMPOSITIONS: TypographyComposition[] = [
  ...modern,
  ...elegant,
  ...bold,
  ...playful,
  ...minimal,
  ...editorial,
  ...street,
  ...luxury,
];

export function getCompositionsByCategory(
  category: TypographyComposition["category"]
): TypographyComposition[] {
  return TYPOGRAPHY_COMPOSITIONS.filter((c) => c.category === category);
}

export function getCompositionById(
  id: string
): TypographyComposition | undefined {
  return TYPOGRAPHY_COMPOSITIONS.find((c) => c.id === id);
}
